FROM php:8.1.1-alpine3.15

RUN apk add --no-cache --update git openssh libzip-dev zip

RUN docker-php-ext-install sockets bcmath zip \
    && docker-php-ext-enable sockets bcmath zip

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && chmod +x composer.phar && mv composer.phar /usr/bin/composer

RUN mkdir /app
WORKDIR /app